#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-actions-ui"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-actions-db"
database_id = "a361ed87-4f27-4b23-9658-fec49113df85"

[vars]
API_KEY = "change-me-in-production"
